### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by wangkaihong** [hivefive08/cs506-final-project#1]
Hi,

The project has a strong motivation, but adding more details would help to eliminate ambiguity and clearly define its scope. For instance, consider addressing the following points:

1. Where will the data be sourced from? What is the nature of the data? What will the labels represent? Are the features numerical, categorical, or a mix of both?
2. Will the data be ready to use as-is, or will it require preprocessing steps? If so, what specific preprocessing will be necessary?
3. How will you measure your model’s performance, and what will you compare it against? Do you have a specific baseline or benchmark that you aim to surpass to validate the effectiveness of your approach?

**Comment by hivefive08** [comment]
It's not letting me add you as a assignee on my pull request
